name: CI - Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: teachpost
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run containers with Docker Compose
        run: |
          docker compose up -d --build

      - name: Wait for backend to be healthy
        run: |
          until curl -s http://localhost:3000/health; do
            echo "Waiting for backend..."
            sleep 5
          done

      - name: Run backend tests
        run: |
          docker compose exec -T backend npm run test || echo "No tests configured"

      - name: Tear down containers
        run: |
          docker compose down -v --remove-orphans
